export const InitialValuesCrew = {
  id: "",
  full_name: "",
  birth_date: "",
  phone: "",
  bank_id: "",
  bank_acc_num: "",
  bank_acc_name: "",
  province: "",
  city: "",
  district: "",
  subdistrict: "",
  address: "",
  username: "",
  kom: 0,
  hmc: 0,
  baptis: 0,
  orientasi: 0,
  photo: "",
  status: 1,
  role: "",
  email: "",
};
